site_name: backend
site_description: manage co-living aparatment
repo_url: https://github.com/ayooby/co-living-managment
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/ayooby">ayooby</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
