# Generated by Django 3.0.2 on 2020-02-15 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cleaner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaner', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('lt', 'Liter'), ('pcs', 'PCS'), ('kg', 'KG')], max_length=3, verbose_name='Item Type')),
                ('category', models.CharField(choices=[('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('house-keeping', 'House Keeping'), ('room', 'Room')], max_length=20, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.PositiveIntegerField(blank=True, null=True, verbose_name='In Use')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='In Stock')),
                ('std', models.PositiveIntegerField(verbose_name='STD')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.Apartment')),
                ('supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.Supply')),
            ],
        ),
    ]
