# Generated by Django 3.0.2 on 2020-02-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20200215_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentsupply',
            old_name='std',
            new_name='standard',
        ),
    ]
