# Generated by Django 3.0.2 on 2020-02-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cleaner',
            field=models.BooleanField(default=False),
        ),
    ]
